# Generated by Django 5.1 on 2024-08-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=256)),
                ('task_description', models.TextField()),
                ('task_state', models.BooleanField()),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
